app:
  build: ./app
  volumes:
    - "app:/src/app"
  ports:
    - "80:3000"
    - "81:9000"
  links:
   - db
db:
  build: ./docker/postgres
  ports:
    - "5433:5432"
  volumes_from:
    - dbdata
dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: true
